# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PersonalBlog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PersonalBlog
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'Purchases'
pod 'SDWebImage'

end
